### ISSUE TITLE
Routing breaks session based pooling when prepared statements are used

### ISSUE THREAD

**Issue by gilesw** [awslabs/pgbouncer-rr-patch#14]
When routing rules are enabled I get an error about a statement not existing.

```
def routing_rules(username, query):
    if "select" in query:
        return "read"
    elif "SELECT" in query:
        return "read"
    else:
        return "write"
```

I've forced to always use the same database and I don't get the error

```
def routing_rules(username, query):
    if "select" in query:
        return "write"
    elif "SELECT" in query:
        return "write"
    else:
        return "write"
```

So I'm guessing the statement is prepared on one backend and then run on another.

**Comment by rstrahan** [comment]
_> So I'm guessing the statement is prepared on one backend and then run on another._

Yes, quite possibly that's what's happening.
You want the routing function to determine the target based only on the prepare statement, and to leave that target unchanged for bind/execute statements. 

You can troubleshoot using the pgbouncer log (run in verbose logging mode) to examine the statements and the routing decisions. You can also add print statements to the routing function to augment the standard logs and trace the routing choices made by your function.  

Can you update the function to explicitly match for prepare statements only - ie detect read versus write by looking for each explicitly, and when neither match is encountered, then return _None_ as the default. (When the pgbouncer-rr code gets a NULL (python None) back, it leaves the target database pool unchanged, which i think is what you want in this case to ensure routing choices are made only on prepare statements.

```
	dbname = pycall(client, client->auth_user->name, query_str, cf_routing_rules_py_module_file,
			"routing_rules");
	if (dbname == NULL) {
		slog_debug(client, "routing_rules returned 'None' - existing connection preserved");
		free(dbname);
		return false;
	}

```
Hope this makes sense. Let us know if you get it working.

**Comment by gilesw** [comment]
Interesting, I'll certainly give that a try. However, I suspect that there are bigger problems afoot. In session mode you get BEGIN and COMMIT as separate queries so these would need to match the server where the transaction queries are run. So I suspect that session mode simply isn't going to work. I've not used transaction mode but I assume it handles transactions as a single operation against the same backend.

**Comment by rstrahan** [comment]
_> So I suspect that session mode simply isn't going to work. I've not used transaction mode but I assume it handles transactions as a single operation against the same backend._

Yes, you are correct. In fact, even transaction mode will be problematic if statements are rerouted mid-transaction. Statement mode is the safest. In the blog / README, I'd briefly noted:

> Ideally queries should autocommit each statement. Set pool_mode = statement in the configuration.
> Multi-statement transactions will work correctly only if statements are not rerouted by the routing_rules function to a different server pool mid-transaction. Set pool_mode = transaction in the configuration.

So bottom line is that any multi-statement transaction (including, in your case, the prepare/bind/execute cycle) needs careful handling in the routing function to ensure transactions aren't broken apart. 

Do please post an update to let us know how you get on with an enhanced version of your routing function. Good luck.

**Comment by rstrahan** [comment]
thread inactive - closing
