### ISSUE TITLE
Packaging pgbouncer-rr into Debian package

### ISSUE THREAD

**Issue by glebmezh** [awslabs/pgbouncer-rr-patch#17]
Has anyone packaged pgbouncer-rr into a Debian package that can be installed with apt-get?

Cloning two repos and compiling the pgbouncer-rr on production seems very risky.

**Comment by rstrahan** [comment]
Not that I'm aware. Perhaps you can be the pioneer, and share back?

**Comment by rstrahan** [comment]
thread inactive - closing
