### ISSUE TITLE
Include pgbouncer license

### ISSUE THREAD

**Issue by pnorman** [awslabs/pgbouncer-rr-patch#2]
The diff files contain code from pgbouncer - more pgbouncer code than new code.

The pgbouncer license requires that the notice https://github.com/pgbouncer/pgbouncer/blob/master/COPYRIGHT is distributed with this code

**Comment by rstrahan** [comment]
Thanks Paul - You are quite correct. 
I have committed a corrected version of LICENSE.txt which should address the issue. Thanks for pointing it out.
