### ISSUE TITLE
get selected database in rewrite_query function

### ISSUE THREAD

**Issue by KlemenSpruk** [awslabs/pgbouncer-rr-patch#29]
Hello!

In pgbouncer instance with pgbouncer-rr-patch installed I have database configuration like this 

[databases]
\* = host=localhost port=5432

On localhost I'm running postgresql with several databases like database_company_one, database_company_two, database_company_three, ...

In my rewrite_query python function I would like to get info to which database the current query will be executed. rewrite_query function supports only two arguments: username, query. 

Is it possible to get info in rewrite_query function on which DB query will be executed?

Thank, Klemen!

**Comment by rstrahan** [comment]
Hi @KlemenSpruk - I think this would be possible, but you'd have to modify the C code to i) call 'route_client_connection() before calling rewrite_query() (client.c), ii) pass dbname (as retuened by route_client_connection()) as a parameter into rewrite_query()
Have a go, and let us know how you get on.
Cheers
Bob

**Comment by yiga2** [comment]
@rstrahan Not everyone is a C developer - any chance you could make it a feature request for someone to pick up ? We are also interested in that small - apparently - enhancement.
