### ISSUE TITLE
Use the same license as pgbouncer

### ISSUE THREAD

**Issue by pnorman** [awslabs/pgbouncer-rr-patch#3]
I want to make use of pgbouncer-rr, but can't with its current license, for a few reasons

- In development my software runs locally, without reference to AWS. If I was rewriting queries, I couldn't test this in development or with CI

-  The use of a non-OSI approved license would require review by many companies legal teams, which it would probably not pass

- If I require rr functionality, it prevents releasing the entire stack I'm using as open source

- I'm targeting organizations which have a requirement to use open source software. This rules out rr as it stands

- Not all potential users of what I develop are on AWS

-----

Better than switching the license here would be integration upstream, but the first step to that would be using the same license.

A less desirable but somewhat usable option would be to use a different open source license.

**Comment by pnorman** [comment]
I did realize that it would be possible to refuse the license and use the generic Github permission to view and fork and instruct users to do the same, which would allow use without using AWS, but then I couldn't package my project and distribute the packages. Also such a route is a dead-end for building a project and getting others to use it.

**Comment by rstrahan** [comment]
My apologies Paul - Our intended use for this software is only with Amazon services, platforms, and applications.

**Comment by pnorman** [comment]
> Our intended use for this software is only with Amazon services, platforms, and applications

That may be the target you had when writing, but there's nothing preventing you from sharing with the community as open-source software.

**Comment by lij55** [comment]
Hi,
This patch is absolutely great. I totally understand the intent of this project and respect the work of AWS. However, this license seems not quite as friendly as opensource software.  It even prevents us from adding a similar feature to pgbouncer.

We'd like to rewrite such features for pgbouncer from the ground up but it is impossible to prove to the lawyer that the re-writing is not kind of "derivative works". I believe it is not what you expected, as an opensource project that derived benefit from the whole pgbouncer community.

I don't mean to require a new license. I just wonder whether it is possible to make it more friendly for the community. I believe the continuous contribution of the community would also help the could migration of AWS. 
Thanks.

**Comment by n-oden** [comment]
At the risk of shouting into the void: it's a crying shame that this patch can't be merged upstream to pgbouncer with the current license, especially now that @ibot3 and others have gone to the effort of porting it to python3 and providing a possible fix for the transaction-awareness issue.

This functionality is not, as far as I can tell, some sort of competitive advantage for amazon: Pgpool-II provides load-balancing functionality and a number of other projects support rules-based query rewriting/routing.  It's a very nice-to-have feature for pgbouncer which at the moment can only be used in front of rds/redshift/aurora.

**Comment by memory** [comment]
I am happy to note that https://github.com/awslabs/pgbouncer-rr-patch/pull/73 converts this to the Apache license, and it should now be possible for the code to be properly integrated with upstream pgbouncer.
