### ISSUE TITLE
Initial connection doesn't utilize routing for fallback database

### ISSUE THREAD

**Issue by joshsouza** [awslabs/pgbouncer-rr-patch#30]
My team has encountered a somewhat odd behavior that differed from our expectations using pgbouncer-rr, and as a result would like to know if it is something that can be addressed in this codebase, or if it is outside of the scope of possibility here.

Summary: When users initially connect to PGBouncer under md5 authentication, the password will be checked against PGBouncer's `users.txt`, and then against the database they requested to connect to. If you are utilizing a [fallback database](https://pgbouncer.github.io/config.html#section-databases), and the user's requested database is not a match, the credentials will be tested against that fallback database. Should that be successful, subsequent _queries_ will be routed according to the `routing_rules.py` logic, which may or may not be the same as the fallback database. The catch here is that if those credentials are not in the fallback database, but are in the database they would be routed to by `routing_rules.py`, authentication will fail.

Our setup:
We have multiple different backend databases, and would like to route users to the correct database based on identifiers in their username (a form of sharding). We would prefer to ignore the requested database name users provide, and rely on a combination of the `routing_rules.py` and the fallback database name to connect them to the proper shard.
`user1` on `shard1` should be able to connect, requesting database `mydatabase` (not in the database list), and be authenticated by and have queries routed to `shard1`.
`user2` on `shard2` should be able to connect, requesting database `mydatabase`, and be authenticated by and have queries routed to `shard2`.
The fallback database is set to `shard1`.

When `user1` connects, their credentials pass PGBouncer's validation (md5), and are then verified on the fallback database (`shard1`), and are properly connected/routed to `shard1` after that.
When `user2` connects, their credentials pass PGBouncer's validation (md5), and are then verified on the fallback database (`shard1`), and authentication fails. They are then disconnected.
If, however, we add `user2`'s credentials to `shard1`, then:
When `user2` connects, their credentials pass PGBouncer's validation (md5), and are then verified on the fallback database (`shard1`) successfully, and subsequent queries are properly routed to `shard2`.

(Also of note, if `user1` requests to connect to `shard2`, since it is in the database list, they will be authenticated against `shard2` and experience the same authentication failure).

I'm not sure if there is any way to ensure that the `routing_rules.py` occurs during/before the authentication step, but I figured I'd make sure you were aware of the situation, and hopefully we can either find a solution, or have some documentation added letting others know this edge case exists.

(For now valid workarounds are to either add all your creds to all your backends, or to ensure that you're not using the fallback database)

Thanks!

**Comment by rstrahan** [comment]
Thanks @joshsouza ! This is a great write up.  They routing_rule.py function is called only when a SQL statement is received on an existing client connection (to the default database pool), so you're right - the user credentials need to be valid on both the default database (for initial connection) and any additional databases used by subsequent reroutes. 

> I'm not sure if there is any way to ensure that the routing_rules.py occurs during/before the authentication step.

I'm not sure either.. I'd guess that this should be possible, but you'd have to dive into the pgbouncer  code to find out where to intercept the initial connection setup, and inject the call to routing_rules.py.  Keep us posted!
