### ISSUE TITLE
Is it possible to send queries to multiple databases behind the scenes?

### ISSUE THREAD

**Issue by Taytay** [awslabs/pgbouncer-rr-patch#31]
The docs mention the possibilities of an A/B test. Is it possible to configure this to in any way send the same query to multiple databases simultaneously? I realize that the caller wouldn't realize that this was happening, but this would be an ideal way to test a new DB configuration, by putting another copy of the database behind pgbouncer-rr, and then running all queries through the primary and the test DB simultaneously.

**Comment by rstrahan** [comment]
Hi @Taytay - as you note, the calling client could only support one target database, however, you could potentially capture the query statement in your routing or rewriting python function, and pass it to another process that would act as a new client to replace the query to additional databases. I haven't done this, but I think it should be doable. Good luck.

**Comment by Taytay** [comment]
Thanks very much! I'll close this.
