### ISSUE TITLE
Patch 1.10.0

### ISSUE THREAD

**Issue by imranismail** [awslabs/pgbouncer-rr-patch#39]
@rstrahan are there any plans to patch 1.10.0?

**Comment by rstrahan** [comment]
No current plans, @imranismail .. I see you sent a PR for this - thanks!
Can you share more info please: 
- why is patch needed? What broke in 1.10.0?
- briefly enumerate the fixes did you made in the PR
With this info i'll try to find time soon to validate and merge. Thank you!
Cheers
Bob

**Comment by imranismail** [comment]
I just tried with the current master and it seems to work. I figured there's three changes in the files RR patches and maybe redoing the patch would be needed.
