### ISSUE TITLE
strip_newlines question

### ISSUE THREAD

**Issue by pnorman** [awslabs/pgbouncer-rr-patch#5]
I see the strip_newlines function is intended to remove newlines from a SQL statement. Is it intended to leave the statement runnable? I had a look through it and it looked like it wasn't intended to change the meaning, but I it does.

If it is intendend to change the meaning, then neglect cases 2 and 3, but 1 could still cause confusion reading logs

```c
char *strip_newlines(char *s) {
	char *p1;
	for (p1 = s; *p1; p1++) {
		if (*p1 == '\n') {
			*p1 = ' ';
		}
	}
	return s;
}
```

A newline can have semantic meaning in a couple of cases

1. comments
  ```sql
select foo -- silly name
from bar;
```

  would become 

  ```sql
select foo -- silly name from bar;
```

2. Within text constants

  ```sql
foo || E'
' || bar
```
  would become
  ```sql
foo || E '' || bar
```

3. Within quoted identifiers
  ```sql
select p AS "a strange
multiline name" FROM foo
```
  would become 
  ```sql
select p AS "a strange multiline name" FROM foo
```

If changing the meaning of the query is okay, then 2 and 3 aren't issues, but 1 still can be

Consider
```sql
SELECT * 
FROM foo
WHERE cond1
-- AND cond2
AND cond3
```

After newline replacement, this is impossible to tell apart from

```sql
SELECT * 
FROM foo
WHERE cond1
-- AND cond2 AND cond3
```

But the two obviously can have a very different meaning.

And yes, I'm crazy enough to have done both 2 and 3.

**Comment by rstrahan** [comment]
Thanks Paul - these are good points. 

The strip_newlines function is used only to make queries printable by the pgbouncer slog_debug() function (it doesn't work with embedded newlines) - the intent is not to change the semantics of the query, but as you point out, it could do so in the examples you have illustrated. 

Interestingly, your examples with comments work OK from the psql client:
```sql
   select * --comment
   from tablea
```
as the comments are stripped before the query is sent..  However, other clients may not behave the same way (dbVisualizer does not) so it remains a valid concern

I'll leave the issue open for now, and I'll fix this soon - probably by stripping newlines only for the purposes of logging, while leaving the active query string untouched.

Thanks again for spotting and logging the issue, Paul. Very much appreciated!

**Comment by rstrahan** [comment]
The latest commit of src/rewrite_query.c now strips newlines from the query string only for the purpose of logging. The query sent to the server is left with newlines intact, so as to preserve query semantics in all cases. 
I tested the fix for each of the cases you noted above. 
The debug log, however, may remain a little misleading in these cases, since I have to strip the newlines in order to get pgbouncer's slog_debug() function to work.
Again, thanks for spotting and reporting this, Paul.
