### ISSUE TITLE
build error ubuntu 14.04

### ISSUE THREAD

**Issue by softapps** [awslabs/pgbouncer-rr-patch#6]
pgbouncer$ make
     CCLD     pgbouncer
.objs/pgbouncer/src/pycall.o: In function `pycall':
/home/serveradmin/pgb/pgbouncer/src/pycall.c:37: undefined reference to `Py_Initialize'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:40: undefined reference to `PySys_SetArgv'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:43: undefined reference to `PyString_FromString'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:44: undefined reference to `PyImport_Import'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:51: undefined reference to `PyObject_GetAttrString'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:57: undefined reference to `PyCallable_Check'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:65: undefined reference to `PyTuple_New'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:66: undefined reference to `PyString_FromString'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:67: undefined reference to `PyTuple_SetItem'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:68: undefined reference to `PyString_FromString'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:69: undefined reference to `PyTuple_SetItem'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:70: undefined reference to `PyObject_CallObject'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:77: undefined reference to `PyString_AsString'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:78: undefined reference to `PyString_AsString'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:84: undefined reference to `PyErr_Occurred'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:85: undefined reference to `PyErr_Fetch'
/home/serveradmin/pgb/pgbouncer/src/pycall.c:86: undefined reference to `PyString_AsString'
collect2: error: ld returned 1 exit status
make: *** [pgbouncer] Error 1

**Comment by rstrahan** [comment]
Per http://ubuntuforums.org/showthread.php?t=1967950, Ubuntu has a dependency on compiler/linker flags. 
Issue fixed in latest checkin, which is also updated to be compatible with pgbouncer v1.7.1
Thanks for reporting the issue!

**Comment by rstrahan** [comment]
For reference, here are the package pre-requisites for building on Ubuntu:
sudo apt-get update
sudo apt-get install libevent-dev  	
sudo apt-get install libssl-dev		
sudo apt-get install git		
sudo apt-get install libtool 	
sudo apt-get install python-dev	
sudo aptitude install autoconf		
sudo apt-get install pkg-config		
sudo apt-get install make
