### ISSUE TITLE
Postgres Version 14 Supported ?

### ISSUE THREAD

**Issue by tocaleb** [awslabs/pgbouncer-rr-patch#65]
Is this compatible with Postgres 14?

**Comment by yahavb** [comment]
Should work. Try to modify https://github.com/awslabs/pgbouncer-rr-patch/blob/873887329cf4a5f9cd5366638c79c43ffd38ec91/Dockerfile#L5
That line should do:

```
RUN git clone https://github.com/pgbouncer/pgbouncer.git --branch "pgbouncer_1_14_0" && \
```

**Comment by yahavb** [comment]
closing it for now. Pls reopen if you have an issue
