### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by softapps** [awslabs/pgbouncer-rr-patch#9]
Currently it is not possible to send database name in the routing_rules i.e routing_rules(username, query), is it possible to add this feature.

**Comment by rstrahan** [comment]
Can you please share your use case? Why do you want the database name passed to the routing_rules function?

The code in route_connection.c could get the database name from the current pool referenced in the client struct, and that could be passed to the python function.. however:
-  each time a query is rerouted, this will change, i.e. the function will always get the database name used for the previous query for this client. Is that the behavior you desire?
- any change would need to be backward compatible with existing functions that accept just the two parameters

**Comment by rstrahan** [comment]
Closed - no response from submitter.
